import type { Metadata } from 'next';
import '@/styles/globals.css';
import '@/styles/dark.css';
import '@/styles/light.css';
import { ThemeProvider } from '@/components/features/theme-provider';
import Header from '@/components/layout/header';

export const metadata: Metadata = {
	title: 'Stats',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className="antialiased">
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					disableTransitionOnChange
				>
					<Header />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
